name: Deploy Google Apps Script

on:
  push:
    branches:
      - main
    paths:
      - 'src/apps-script/**'
      - '.github/workflows/deploy-apps-script.yml'
  workflow_dispatch:

env:
  SCRIPT_ID: '1ih6hahfWWHXXaRdZ7gq3VTYSFS8-88mqKJTRJoBm1l363TosDH_y2tWj'
  DEPLOYMENT_ID: 'AKfycbyWuGn7rigFDy1CQOVuepcSkaouCbUhNw7aeq07clE'

jobs:
  deploy:
    name: Deploy to Google Apps Script
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install
      
      - name: Setup clasp authentication
        run: |
          # Parse and validate JSON credentials
          # Remove potential BOM, trim whitespace, and ensure proper JSON
          echo '${{ secrets.CLASP_CREDENTIALS }}' | sed 's/^\xEF\xBB\xBF//' | tr -d '\r' > ~/.clasprc.json.tmp
          
          # Validate and pretty-print JSON
          if jq . ~/.clasprc.json.tmp > ~/.clasprc.json 2>/dev/null; then
            echo "Successfully parsed and formatted JSON"
          else
            echo "Failed to parse JSON, trying alternative approach"
            # Try removing outer quotes if they exist
            echo '${{ secrets.CLASP_CREDENTIALS }}' | sed 's/^"//;s/"$//' | sed 's/^\xEF\xBB\xBF//' | tr -d '\r' > ~/.clasprc.json
          fi
          
          chmod 600 ~/.clasprc.json
          
          # Also try the newer location
          mkdir -p ~/.config/clasp
          cp ~/.clasprc.json ~/.config/clasp/.clasprc.json
          chmod 600 ~/.config/clasp/.clasprc.json
          
          # Clean up temp file
          rm -f ~/.clasprc.json.tmp
          
      - name: Setup .clasp.json
        run: |
          echo '{
            "scriptId": "${{ env.SCRIPT_ID }}",
            "rootDir": "./src/apps-script"
          }' > .clasp.json
          
      - name: Push to Google Apps Script
        run: npx clasp push --force
      
      - name: Deploy (if deployment ID is set)
        if: env.DEPLOYMENT_ID != ''
        run: |
          echo "Note: The deployment ${{ env.DEPLOYMENT_ID }} appears to be read-only."
          echo "This typically means it's a HEAD deployment or was created manually."
          echo "Creating a new versioned deployment instead..."
          npx clasp deploy --description "GitHub Actions deployment $(date +'%Y-%m-%d %H:%M:%S')"
      
      - name: Cleanup credentials
        if: always()
        run: |
          rm -f ~/.clasprc.json .clasp.json
          rm -f ~/.config/clasp/.clasprc.json